# Auto submit commit / push to pr
name: 提交后自动创建PR请求
on:
  push:
    branches:
      - 'feature/**'
jobs:
  auto_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          delete-branch: true
          base: master
          branch: ${{ github.ref }}
