name: PR 预处理
on:
  push:
    branches:
      - 'feature/**'
    tags-ignore:
      - '*'

jobs:
  merge-branch:
    name: 提交到PR
    runs-on: ubuntu-latest
#    if: github.ref_type != 'branch'
    steps:
      - name: 获取代码
        uses: actions/checkout@master
      - run: echo "${{github.event_name}} ${{github.ref_type}}"
      - name: 提交
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          delete-branch: true
          base: master
          branch: ${{ github.ref }}
          body: "Automated changes by [pre-commit](../blob/master/.github/workflows/${{ github.action_path }}.yaml) action"