name: PR 预处理
on:
  push:
    branches:
      - 'feature/**'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          delete-branch: true
          base: master
          branch: ${{ github.ref }}
          commit-message: "Automated changes by [pre-commit](${{ github.action_path }}) action"